version: '3.8'

services:
  clickhouse:
    build: .
    container_name: clickhouse-server
    ports:
      - "8123:8123"  # HTTP
      - "9000:9000"  # Native TCP
      - "9009:9009"  # Inter-server
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./config:/etc/clickhouse-server/config.d
      - ./users:/etc/clickhouse-server/users.d
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  clickhouse_data:
